### ISSUE TITLE
Error when the bot tries to play something

### ISSUE THREAD

**Issue by Hoyle95** [maxcutlyp/YoutubeBot#23]
Hello I have the bot set up, it connects / logs in and downloads a video when i give it a play command with a youtube link, the problem is when it joins the voice call, I get this error:

```
2024-07-28 19:31:30 INFO     discord.voice_state Voice connection complete.
unhandled command error raised, err=CommandInvokeError('Command raised an exception: ClientException: ffmpeg was not found.')2024-07-28 19:31:30 ERROR    discord.client Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\matth\git\YoutubeBot\youtubebot.py", line 210, in on_command_error
    sp.run(['./restart'])
  File "C:\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

I would appreciate any help on the matter, I am on windows 11, running it as admin in a power shell cheers!

**Comment by Hoyle95** [comment]
The issue was FFmpeg not correctly being installed on my system, I reinstalled it through choco & everything is working fine now :) 

thank you for the wonderful code!
